CREATE TABLE `barrierIntegrations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(100) NOT NULL,
	`type` enum('came','nice','bft','doorhan','gpio','custom_http') NOT NULL,
	`isActive` boolean NOT NULL DEFAULT false,
	`isPrimary` boolean NOT NULL DEFAULT false,
	`host` varchar(255),
	`port` int,
	`username` varchar(100),
	`password` varchar(255),
	`apiEndpoint` text,
	`apiKey` varchar(255),
	`openCommand` varchar(255),
	`closeCommand` varchar(255),
	`statusCommand` varchar(255),
	`gpioPin` int,
	`gpioActiveHigh` boolean DEFAULT true,
	`openDuration` int DEFAULT 5000,
	`timeout` int DEFAULT 10000,
	`lastStatus` enum('online','offline','error','unknown') DEFAULT 'unknown',
	`lastStatusCheck` timestamp,
	`lastError` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `barrierIntegrations_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `cameraIntegrations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(100) NOT NULL,
	`type` enum('hikvision','dahua','axis','onvif','custom_rtsp','custom_http') NOT NULL,
	`isActive` boolean NOT NULL DEFAULT false,
	`isPrimary` boolean NOT NULL DEFAULT false,
	`host` varchar(255),
	`port` int,
	`username` varchar(100),
	`password` varchar(255),
	`rtspUrl` text,
	`httpSnapshotUrl` text,
	`streamChannel` int DEFAULT 1,
	`streamSubtype` int DEFAULT 0,
	`recognitionEnabled` boolean DEFAULT true,
	`recognitionInterval` int DEFAULT 2000,
	`recognitionConfidenceThreshold` int DEFAULT 70,
	`lastStatus` enum('online','offline','error','unknown') DEFAULT 'unknown',
	`lastStatusCheck` timestamp,
	`lastError` text,
	`lastSnapshot` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `cameraIntegrations_id` PRIMARY KEY(`id`)
);
